<?php
$isitma_verileri=array(
    'Belirtilmemiş',
    'Klima',
    'Kalorifer',
    'Kombi',
    'Yerden Isıtma',
    'Doğalgaz',
    'Doğalgaz Kapıda',
    'Doğalgaz Soba',
    'Merkezi Doğalgaz',
    'Güneş Enerjisi',
    'soba'
);
$ayrintilar=array(
 	'Krediye Uygun',
	'Dubleks',
	'Ters Dubleks',
	'Çatı Dubleksi',
	'Tripleks',
	'Ters Tripleks',
	'Teraslı',
	'Müstakil Bahçeli',
	'Çelik Kapı',
	'Duşakabin',
	'Çift Banyo',
	'Jakuzi',
	'Şömine',
	'Mobilya',
	'Beyaz Eşya',
	'Ankastre Mutfak',
	'Deniz Manzarası',
	'Boğaz Manzarası',
	'Doğa Manzarası',
	'Site İçerisinde',
	'Depreme Dayanıklı',
	'Asansör',
	'Jeneratör',
	'Su Deposu',
	'Hidrofor',
	'Uydu',
	'Kablo TV',
	'Güvenlik',
	'Kapıcı',
	'Otopark',
	'Kapalı Otopark',
	'Çocuk Parkı',
	'Yangın Merdiveni',
	'Yüzme Havuzu',
	'Panjur',
	'PVC Pencere',
	'Aluminyum Pencere',
	'Çift Kat Cam',
	'Balkon',
	'Alarm',
	'Kartonpiyer',
	'Spot Işık',
	'Klima',
	'Yüksek Tavan'
)
?>
