<?php
$isitma_verileri=array(
    'Belirtilmemiþ',
    'Klima',
    'Kalorifer',
    'Kombi',
    'Yerden Isýtma',
    'Doðalgaz',
    'Doðalgaz Kapýda',
    'Doðalgaz Soba',
    'Merkezi Doðalgaz',
    'Güneþ Enerjisi',
    'Soba'
);
$ayrintilar=array(
 	'Krediye Uygun',
	'Dubleks',
	'Ters Dubleks',
	'Dubleksi',
	'Tripleks',
	'Ters Tripleks',
	'Teraslý',
	'Müstakil Bahçeli',
	'Çelik Kapý',
	'Duþakabin',
	'Çift Banyo',
	'Jakuzi',
	'Þömine',
	'Mobilya',
	'Beyaz Eþya',
	'Ankastre Mutfak',
	'Deniz Manzarasý',
	'Boðaz Manzarasý',
	'Doða Manzarasý',
	'Site Ýerisinde',
	'Depreme Dayanýklý',
	'Asansör',
	'Jeneratör',
	'Su Deposu',
	'Hidrofor',
	'Uydu',
	'Kablo TV',
	'Güvenlik',
	'Kapýcý±',
	'Otopark',
	'Kapalý Otopark',
	'Çocuk Parký',
	'Yangýn Merdiveni',
	'Yüzme Havuzu',
	'Panjur',
	'PVC Pencere',
	'Aluminyum Pencere',
	'Çift Kat Cam',
	'Balkon',
	'Alarm',
	'Kartonpiyer',
	'Spot Iþýk',
	'Klima',
	'Yüksek Tavan'
)
?>
